services:
  db:
    container_name: mysql_contain
    image: mysql
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      # - ./db:/var/lib/mysql
      - type: bind 
        source: ./db
        target: /docker-entrypoint-initdb.d
        # $PWD/db/:/docker-entrypoint-initdb.d/
      
